[project]
name = "mit-6100l"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.9.0",
    "numpy>=2.4.0",
    "pip>=25.3",
    "pytest>=9.0.2",
    "setuptools>=80.9.0",
]
